package org.studt.autozwhimsy;

import com.mojang.datafixers.types.templates.List;
import net.fabricmc.api.ModInitializer;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.tooltip.*;
import net.minecraft.text.Text;
import net.minecraft.world.World;
import org.studt.autozwhimsy.ModItemGroups;
import org.studt.autozwhimsy.items.ModItem;

public class Autozwhimsy implements ModInitializer {


    @Override
    public void onInitialize() {
        ModItemGroups.registerModItemGroups();
        ModItem.initialize();


    }


}

